title: Auto RSS Blog
email: your-email@example.com
description: >-
  A GitHub Pages + Jekyll blog that auto-imports posts from an RSS feed.
baseurl: ""
url: "https://bhashasanskriti.wordpress.com/tag/hindi-grammar/feed/"
theme: minima

plugins:
  - jekyll-feed

posts_dir: _posts
